
import { EducationSystem, Badge, UserProfile } from './types';

export const YEARS = [
  'Grade 1', 'Grade 2', 'Grade 3', 'Grade 4', 'Grade 5', 'Grade 6',
  'Grade 7', 'Grade 8', 'Grade 9', 'Grade 10', 'Grade 11', 'Grade 12',
  'University Year 1', 'University Year 2', 'University Year 3', 'University Year 4'
];

export const SUBJECTS = [
  'Mathematics', 'Physics', 'Chemistry', 'Biology', 'Science', 'French', 'History', 
  'Geography', 'Computer Science', 'English Literature', 'Psychology', 
  'Economics', 'Business Studies'
];

export const EDUCATION_SYSTEMS: EducationSystem[] = [
  EducationSystem.STANDARD,
  EducationSystem.IGCSE,
  EducationSystem.IB,
  EducationSystem.THANAWEYA_AMMA,
  EducationSystem.CAMBRIDGE,
  EducationSystem.AMERICAN
];

// --- Gamification Constants ---

export const XP_REWARDS = {
  GENERATE_NOTE: 20,
  COMPLETE_QUIZ: 50,
  PERFECT_SCORE: 30, // Bonus
  REVIEW_SESSION: 40,
  CHECK_HOMEWORK: 15,
  DAILY_STREAK: 10,
  LISTEN_PODCAST: 25,
  GENERATE_CHEAT_SHEET: 30
};

export const LEVEL_THRESHOLD = 200; // XP needed per level (simplified linear for now)

export const BADGES: Badge[] = [
  {
    id: 'first_step',
    icon: '🚀',
    nameKey: 'badgeFirstStep',
    descKey: 'badgeFirstStepDesc',
    condition: (u, count) => count >= 1
  },
  {
    id: 'streak_3',
    icon: '🔥',
    nameKey: 'badgeStreak3',
    descKey: 'badgeStreak3Desc',
    condition: (u, count) => u.gamification.streak >= 3
  },
  {
    id: 'streak_7',
    icon: '⚡',
    nameKey: 'badgeStreak7',
    descKey: 'badgeStreak7Desc',
    condition: (u, count) => u.gamification.streak >= 7
  },
  {
    id: 'scholar',
    icon: '🎓',
    nameKey: 'badgeScholar',
    descKey: 'badgeScholarDesc',
    condition: (u, count) => u.gamification.level >= 5
  },
  {
    id: 'master',
    icon: '👑',
    nameKey: 'badgeMaster',
    descKey: 'badgeMasterDesc',
    condition: (u, count) => u.gamification.level >= 10
  }
];

export const PLACEHOLDER_IMG = "https://picsum.photos/400/300";

export const TRANSLATIONS = {
  English: {
    appTitle: "StudyGenius AI",
    developedBy: "Developed by Mohamed Eisa",
    menuCreate: "Create",
    menuDashboard: "Study Tracker",
    menuGamification: "Achievements",
    welcomeTitle: "Create Your Study Material",
    welcomeSubtitle: "Configure the AI to generate notes, quizzes, or check your homework.",
    eduLevel: "Education Level",
    curriculum: "Curriculum",
    subject: "Subject",
    other: "Other?",
    list: "List",
    topic: "Topic",
    topicOptional: "(Optional)",
    topicPlaceholder: "e.g. Photosynthesis, Newton's Laws",
    modeNotes: "Study Notes",
    modeQuiz: "Generate Quiz",
    modeHomework: "Homework Checker",
    modeFlashcards: "Flashcards",
    modeLazy: "YouTube / Lazy",
    modePodcast: "AI Podcast",
    modeCheatSheet: "Cheat Sheet",
    language: "Language",
    detailLevel: "Detail Level",
    difficulty: "Difficulty",
    quizType: "Quiz Type",
    numQuestions: "Number of Questions",
    uploadPhoto: "Upload Homework Photo",
    clickUpload: "Click to select an image (JPG, PNG)",
    btnGenerateGuide: "Generate Guide",
    btnGenerateQuiz: "Generate Quiz",
    btnCheckHomework: "Check Homework",
    btnGenerateFlashcards: "Create Cards",
    btnLazy: "Summarize Video",
    btnPodcast: "Create Podcast",
    btnGenerateCheatSheet: "Generate Sheet",
    shareApp: "Share App",
    appLinkCopied: "App link copied!",
    
    // Auth
    loginTitle: "Welcome to StudyGenius",
    loginSubtitle: "Sign in to track your progress and personalize your learning.",
    emailLabel: "Email Address",
    nameLabel: "Your Name",
    prefYearLabel: "Your Grade/Year",
    prefCurrLabel: "Your Curriculum",
    btnLogin: "Start Learning",
    btnGuest: "Continue as Guest",
    welcomeBack: "Welcome back,",
    logout: "Logout",
    or: "Or",
    
    // Dashboard
    perfTrend: "Performance Trend",
    noQuizData: "No quiz data yet.",
    quizzesCompleted: "Quizzes Completed",
    avgScore: "Avg Score",
    recentGen: "Your Study History",
    noActivity: "No recent activity found.",
    noFilterMatch: "No items match your filter.",
    all: "All",
    addTag: "Add Tag",
    doc: "DOC",
    quizShort: "QUIZ",
    chk: "CHK",
    cardShort: "CARD",
    lazyShort: "YT",
    podShort: "POD",
    csShort: "CS",
    aiProgressReport: "AI Progress Tracker",
    generateAnalysis: "Generate Analysis",
    refreshAnalysis: "Update Analysis",
    clickToAnalyze: "Click 'Generate Analysis' to get AI insights",
    noDataYet: "No data available yet",
    overallMastery: "Overall Grade Mastery",
    strengths: "Strengths",
    areasFocus: "Areas for Focus",
    recommendedPlan: "Recommended Plan",
    analysisGenerated: "Analysis generated on",
    generating: "Analyzing...",
    
    // Gamification
    level: "Lvl",
    xp: "XP",
    streak: "Streak",
    trophyRoom: "Trophy Room",
    weeklyChallenge: "Weekly Challenge",
    challengeTitle: "Quiz Master",
    challengeDesc: "Complete 3 quizzes with >80% score this week.",
    challengeReward: "Reward: 500 XP",
    leaderboard: "Class Leaderboard",
    badgeFirstStep: "First Step",
    badgeFirstStepDesc: "Completed your first study activity.",
    badgeStreak3: "On Fire",
    badgeStreak3Desc: "Achieved a 3-day study streak.",
    badgeStreak7: "Unstoppable",
    badgeStreak7Desc: "Achieved a 7-day study streak.",
    badgeScholar: "Scholar",
    badgeScholarDesc: "Reached Level 5.",
    badgeMaster: "Grandmaster",
    badgeMasterDesc: "Reached Level 10.",
    xpGained: "XP Gained!",
    levelUp: "Level Up!",
    
    // Learning Path & Flashcards
    adaptivePath: "Adaptive Learning Path",
    generatePath: "Create AI Study Path",
    pathIntro: "A personalized curriculum based on your weaknesses and goals.",
    startTopic: "Start Topic",
    locked: "Locked",
    completed: "Completed",
    dueFlashcards: "Review Due Cards",
    noDueCards: "All caught up! No cards due.",
    cardsReady: "Cards ready to review",
    reviewNow: "Review Now",
    flashcardReview: "Spaced Repetition Review",
    revealAnswer: "Reveal Answer",
    ratingAgain: "Again (< 1m)",
    ratingHard: "Hard (2d)",
    ratingGood: "Good (3d)",
    ratingEasy: "Easy (4d)",
    regeneratePath: "Refresh Path",
    pathModeWeakness: "Improve Weaknesses",
    pathModeCustom: "Custom Goal",
    pathCustomPlaceholder: "e.g. Prepare for Algebra Finals, Learn about Space...",
    
    // Lazy/YouTube & Podcast
    youtubeUrl: "YouTube Video URL",
    youtubePlaceholder: "https://www.youtube.com/watch?v=...",
    transcriptLabel: "Or Paste Transcript (Optional - for better accuracy)",
    transcriptPlaceholder: "Paste the video transcript here if the video is new or not famous...",
    lazyIntro: "Paste a YouTube link. We'll extract the key lessons and make a quiz.",
    podcastIntro: "Convert any topic into a short, engaging audio podcast. Perfect for commuting!",
    cheatSheetIntro: "Get a dense, one-page summary of key formulas and concepts.",
    podcastTopicPlaceholder: "e.g. The French Revolution, Quantum Mechanics...",
    podcastLength: "Duration",
    podcastVoice: "Voice",
    short: "Short (~1 min)",
    medium: "Medium (~2 mins)",
    long: "Long (~4 mins)",
    male: "Male",
    female: "Female",
    downloadAudio: "Download Audio",
    
    // Common
    back: "Back",
    print: "Print",
    exportPdf: "Export PDF",
    close: "Close",
    generatedWith: "Generated with Gemini AI",

    // Quiz & Audio
    quit: "Quit",
    progress: "Progress",
    switchToFlash: "Switch to Flashcards",
    switchToQuiz: "Switch to Quiz",
    checkAnswer: "Check Answer",
    nextQuestion: "Next Question →",
    seeResults: "See Results",
    quizComplete: "Quiz Complete!",
    reviewComplete: "Review Complete!",
    reviewMistakes: "Review Mistakes",
    retake: "Retake Quiz",
    restartReview: "Restart Review",
    backDashboard: "Back to Tracker",
    aiCoach: "AI Performance Coach",
    analyzing: "Analyzing...",
    accuracy: "Accuracy",
    correct: "Correct",
    questionsToImprove: "questions to improve",
    tryBetter: "Try for a better score",
    tapFlip: "Tap to flip",
    answer: "Answer",
    previous: "Previous",
    next: "Next",
    done: "Done",
    exit: "Exit",
    card: "Card",
    play: "Play",
    pause: "Pause",
    playingPodcast: "Playing Podcast",
    scriptView: "View Script"
  },
  Arabic: {
    appTitle: "StudyGenius AI",
    developedBy: "تم التطوير بواسطة محمد عيسى",
    menuCreate: "إنشاء",
    menuDashboard: "سجل الدراسة",
    menuGamification: "الإنجازات",
    welcomeTitle: "أنشئ موادك الدراسية",
    welcomeSubtitle: "قم بإعداد الذكاء الاصطناعي لإنشاء ملاحظات، اختبارات، أو تصحيح واجبك.",
    eduLevel: "المستوى التعليمي",
    curriculum: "المنهج",
    subject: "المادة",
    other: "أخرى؟",
    list: "قائمة",
    topic: "الموضوع",
    topicOptional: "(اختياري)",
    topicPlaceholder: "مثال: البناء الضوئي، قوانين نيوتن",
    modeNotes: "ملاحظات دراسية",
    modeQuiz: "إنشاء اختبار",
    modeHomework: "مصحح الواجبات",
    modeFlashcards: "بطاقات استذكار",
    modeLazy: "يوتيوب / السريع",
    modePodcast: "بودكاست ذكي",
    modeCheatSheet: "ورقة المراجعة",
    language: "اللغة",
    detailLevel: "مستوى التفصيل",
    difficulty: "الصعوبة",
    quizType: "نوع الاختبار",
    numQuestions: "عدد الأسئلة",
    uploadPhoto: "رفع صورة الواجب",
    clickUpload: "اضغط لاختيار صورة (JPG, PNG)",
    btnGenerateGuide: "إنشاء الدليل",
    btnGenerateQuiz: "إنشاء الاختبار",
    btnCheckHomework: "فحص الواجب",
    btnGenerateFlashcards: "إنشاء البطاقات",
    btnLazy: "تلخيص الفيديو",
    btnPodcast: "إنشاء بودكاست",
    btnGenerateCheatSheet: "إنشاء الورقة",
    shareApp: "مشاركة التطبيق",
    appLinkCopied: "تم نسخ الرابط!",

    // Auth
    loginTitle: "مرحباً بك في StudyGenius",
    loginSubtitle: "سجل الدخول لتتبع تقدمك وتخصيص تجربتك التعليمية.",
    emailLabel: "البريد الإلكتروني",
    nameLabel: "الاسم",
    prefYearLabel: "السنة الدراسية",
    prefCurrLabel: "المنهج الدراسي",
    btnLogin: "ابدأ التعلم",
    btnGuest: "تابع كضيف",
    welcomeBack: "مرحباً بعودتك،",
    logout: "تسجيل خروج",
    or: "أو",
    
    // Dashboard
    perfTrend: "مؤشر الأداء",
    noQuizData: "لا توجد بيانات اختبارات.",
    quizzesCompleted: "الاختبارات المكتملة",
    avgScore: "متوسط الدرجات",
    recentGen: "سجل دراستك",
    noActivity: "لا يوجد نشاط حديث.",
    noFilterMatch: "لا توجد عناصر تطابق الفلتر.",
    all: "الكل",
    addTag: "إضافة وسم",
    doc: "مستند",
    quizShort: "اختبار",
    chk: "واجب",
    cardShort: "بطاقة",
    lazyShort: "يوتيوب",
    podShort: "صوت",
    csShort: "ملخص",
    aiProgressReport: "متتبع التقدم الذكي",
    generateAnalysis: "تحليل التقدم",
    refreshAnalysis: "تحديث التحليل",
    clickToAnalyze: "اضغط 'تحليل التقدم' للحصول على تقرير الذكاء الاصطناعي",
    noDataYet: "لا توجد بيانات متاحة بعد",
    overallMastery: "إتقان المستوى الدراسي",
    strengths: "نقاط القوة",
    areasFocus: "نقاط للتحسين",
    recommendedPlan: "الخطة المقترحة",
    analysisGenerated: "تم إنشاء التحليل في",
    generating: "جاري التحليل...",

    // Gamification
    level: "مستوى",
    xp: "نقاط",
    streak: "حماس",
    trophyRoom: "غرفة الجوائز",
    weeklyChallenge: "التحدي الأسبوعي",
    challengeTitle: "سيد الاختبارات",
    challengeDesc: "أكمل 3 اختبارات بنتيجة أعلى من 80% هذا الأسبوع.",
    challengeReward: "الجائزة: 500 نقطة",
    leaderboard: "لوحة المتصدرين",
    badgeFirstStep: "الخطوة الأولى",
    badgeFirstStepDesc: "أكملت نشاطك الدراسي الأول.",
    badgeStreak3: "مشتعل",
    badgeStreak3Desc: "حققت سلسلة دراسة لمدة 3 أيام.",
    badgeStreak7: "لا يمكن إيقافك",
    badgeStreak7Desc: "حققت سلسلة دراسة لمدة 7 أيام.",
    badgeScholar: "باحث",
    badgeScholarDesc: "وصلت للمستوى 5.",
    badgeMaster: "خبير",
    badgeMasterDesc: "وصلت للمستوى 10.",
    xpGained: "اكتسبت نقاط!",
    levelUp: "مستوى جديد!",

    // Learning Path & Flashcards
    adaptivePath: "مسار التعلم الذكي",
    generatePath: "إنشاء مسار ذكي",
    pathIntro: "منهج مخصص بناءً على نقاط ضعفك وأهدافك.",
    startTopic: "ابدأ الموضوع",
    locked: "مغلق",
    completed: "مكتمل",
    dueFlashcards: "مراجعة البطاقات المستحقة",
    noDueCards: "لا توجد بطاقات مستحقة الآن.",
    cardsReady: "بطاقة جاهزة للمراجعة",
    reviewNow: "ابدأ المراجعة",
    flashcardReview: "مراجعة التكرار المتباعد",
    revealAnswer: "كشف الإجابة",
    ratingAgain: "أعد (< دقيقة)",
    ratingHard: "صعب (يومان)",
    ratingGood: "جيد (3 أيام)",
    ratingEasy: "سهل (4 أيام)",
    regeneratePath: "تحديث المسار",
    pathModeWeakness: "تحسين نقاط الضعف",
    pathModeCustom: "هدف مخصص",
    pathCustomPlaceholder: "مثال: التحضير لاختبار الجبر، تعلم الفضاء...",

    // Lazy/YouTube & Podcast
    youtubeUrl: "رابط فيديو يوتيوب",
    youtubePlaceholder: "https://www.youtube.com/watch?v=...",
    transcriptLabel: "أو الصق النص (اختياري - لدقة أفضل)",
    transcriptPlaceholder: "الصق نص الفيديو هنا إذا كان الفيديو جديداً أو غير مشهور...",
    lazyIntro: "ضع رابط يوتيوب. سنستخرج أهم الدروس وننشئ اختباراً.",
    podcastIntro: "حول أي موضوع إلى بودكاست صوتي قصير. مثالي للمواصلات!",
    cheatSheetIntro: "احصل على ملخص مكثف من صفحة واحدة لأهم القوانين والمفاهيم.",
    podcastTopicPlaceholder: "مثال: الثورة الفرنسية، ميكانيكا الكم...",
    podcastLength: "المدة",
    podcastVoice: "الصوت",
    short: "قصير (دقيقة)",
    medium: "متوسط (دقيقتين)",
    long: "طويل (4 دقائق)",
    male: "رجل",
    female: "امرأة",
    downloadAudio: "تحميل الصوت",
    
    // Common
    back: "رجوع",
    print: "طباعة",
    exportPdf: "تصدير PDF",
    close: "إغلاق",
    generatedWith: "تم الإنشاء بواسطة Gemini AI",

    // Quiz & Audio
    quit: "خروج",
    progress: "التقدم",
    switchToFlash: "التبديل للبطاقات",
    switchToQuiz: "التبديل للاختبار",
    checkAnswer: "تحقق من الإجابة",
    nextQuestion: "السؤال التالي ←",
    seeResults: "عرض النتائج",
    quizComplete: "اكتمل الاختبار!",
    reviewComplete: "اكتملت المراجعة!",
    reviewMistakes: "مراجعة الأخطاء",
    retake: "إعادة الاختبار",
    restartReview: "إعادة المراجعة",
    backDashboard: "عودة للسجل",
    aiCoach: "مدرب الأداء الذكي",
    analyzing: "جاري التحليل...",
    accuracy: "الدقة",
    correct: "صحيح",
    questionsToImprove: "أسئلة للتحسين",
    tryBetter: "حاول الحصول على درجة أفضل",
    tapFlip: "اضغط للقلب",
    answer: "الإجابة",
    previous: "السابق",
    next: "التالي",
    done: "تم",
    exit: "خروج",
    card: "بطاقة",
    play: "تشغيل",
    pause: "إيقاف",
    playingPodcast: "تشغيل البودكاست",
    scriptView: "عرض النص"
  }
};
