

import { EducationSystem } from './types';

export const YEARS = [
  'Grade 1', 'Grade 2', 'Grade 3', 'Grade 4', 'Grade 5', 'Grade 6',
  'Grade 7', 'Grade 8', 'Grade 9', 'Grade 10', 'Grade 11', 'Grade 12',
  'University Year 1', 'University Year 2', 'University Year 3', 'University Year 4'
];

export const SUBJECTS = [
  'Mathematics', 'Physics', 'Chemistry', 'Biology', 'History', 
  'Geography', 'Computer Science', 'English Literature', 'Psychology', 
  'Economics', 'Business Studies'
];

export const EDUCATION_SYSTEMS: EducationSystem[] = [
  EducationSystem.STANDARD,
  EducationSystem.IGCSE,
  EducationSystem.IB,
  EducationSystem.THANAWEYA_AMMA,
  EducationSystem.CAMBRIDGE
];

// Fallback images if needed
export const PLACEHOLDER_IMG = "https://picsum.photos/400/300";

export const TRANSLATIONS = {
  English: {
    appTitle: "StudyGenius AI",
    developedBy: "Developed by Mohamed Eisa",
    menuCreate: "Create",
    menuDashboard: "Study Tracker",
    welcomeTitle: "Create Your Study Material",
    welcomeSubtitle: "Configure the AI to generate notes, quizzes, or check your homework.",
    eduLevel: "Education Level",
    curriculum: "Curriculum",
    subject: "Subject",
    other: "Other?",
    list: "List",
    topic: "Topic",
    topicOptional: "(Optional)",
    topicPlaceholder: "e.g. Photosynthesis, Newton's Laws",
    modeNotes: "Study Notes",
    modeQuiz: "Generate Quiz",
    modeHomework: "Homework Checker",
    language: "Language",
    detailLevel: "Detail Level",
    difficulty: "Difficulty",
    quizType: "Quiz Type",
    numQuestions: "Number of Questions",
    uploadPhoto: "Upload Homework Photo",
    clickUpload: "Click to select an image (JPG, PNG)",
    btnGenerateGuide: "Generate Guide",
    btnGenerateQuiz: "Generate Quiz",
    btnCheckHomework: "Check Homework",
    shareApp: "Share App",
    appLinkCopied: "App link copied!",
    
    // Auth
    loginTitle: "Welcome to StudyGenius",
    loginSubtitle: "Sign in to track your progress and personalize your learning.",
    emailLabel: "Email Address",
    nameLabel: "Your Name",
    prefYearLabel: "Your Grade/Year",
    prefCurrLabel: "Your Curriculum",
    btnLogin: "Start Learning",
    btnGuest: "Continue as Guest",
    welcomeBack: "Welcome back,",
    logout: "Logout",
    or: "Or",
    
    // Dashboard
    perfTrend: "Performance Trend",
    noQuizData: "No quiz data yet.",
    quizzesCompleted: "Quizzes Completed",
    avgScore: "Avg Score",
    recentGen: "Your Study History",
    noActivity: "No recent activity found.",
    noFilterMatch: "No items match your filter.",
    all: "All",
    addTag: "Add Tag",
    doc: "DOC",
    quizShort: "QUIZ",
    chk: "CHK",
    aiProgressReport: "AI Progress Tracker",
    generateAnalysis: "Generate Analysis",
    refreshAnalysis: "Update Analysis",
    clickToAnalyze: "Click 'Generate Analysis' to get AI insights",
    noDataYet: "No data available yet",
    overallMastery: "Overall Grade Mastery",
    strengths: "Strengths",
    areasFocus: "Areas for Focus",
    recommendedPlan: "Recommended Plan",
    analysisGenerated: "Analysis generated on",
    generating: "Analyzing...",
    
    // Common
    back: "Back",
    print: "Print",
    exportPdf: "Export PDF",
    close: "Close",
    generatedWith: "Generated with Gemini AI",

    // Quiz
    quit: "Quit",
    progress: "Progress",
    switchToFlash: "Switch to Flashcards",
    switchToQuiz: "Switch to Quiz",
    checkAnswer: "Check Answer",
    nextQuestion: "Next Question →",
    seeResults: "See Results",
    quizComplete: "Quiz Complete!",
    reviewComplete: "Review Complete!",
    reviewMistakes: "Review Mistakes",
    retake: "Retake Quiz",
    restartReview: "Restart Review",
    backDashboard: "Back to Tracker",
    aiCoach: "AI Performance Coach",
    analyzing: "Analyzing...",
    accuracy: "Accuracy",
    correct: "Correct",
    questionsToImprove: "questions to improve",
    tryBetter: "Try for a better score",
    tapFlip: "Tap to flip",
    answer: "Answer",
    previous: "Previous",
    next: "Next",
    done: "Done",
    exit: "Exit",
    card: "Card"
  },
  Arabic: {
    appTitle: "StudyGenius AI",
    developedBy: "تم التطوير بواسطة محمد عيسى",
    menuCreate: "إنشاء",
    menuDashboard: "سجل الدراسة",
    welcomeTitle: "أنشئ موادك الدراسية",
    welcomeSubtitle: "قم بإعداد الذكاء الاصطناعي لإنشاء ملاحظات، اختبارات، أو تصحيح واجبك.",
    eduLevel: "المستوى التعليمي",
    curriculum: "المنهج",
    subject: "المادة",
    other: "أخرى؟",
    list: "قائمة",
    topic: "الموضوع",
    topicOptional: "(اختياري)",
    topicPlaceholder: "مثال: البناء الضوئي، قوانين نيوتن",
    modeNotes: "ملاحظات دراسية",
    modeQuiz: "إنشاء اختبار",
    modeHomework: "مصحح الواجبات",
    language: "اللغة",
    detailLevel: "مستوى التفصيل",
    difficulty: "الصعوبة",
    quizType: "نوع الاختبار",
    numQuestions: "عدد الأسئلة",
    uploadPhoto: "رفع صورة الواجب",
    clickUpload: "اضغط لاختيار صورة (JPG, PNG)",
    btnGenerateGuide: "إنشاء الدليل",
    btnGenerateQuiz: "إنشاء الاختبار",
    btnCheckHomework: "فحص الواجب",
    shareApp: "مشاركة التطبيق",
    appLinkCopied: "تم نسخ الرابط!",

    // Auth
    loginTitle: "مرحباً بك في StudyGenius",
    loginSubtitle: "سجل الدخول لتتبع تقدمك وتخصيص تجربتك التعليمية.",
    emailLabel: "البريد الإلكتروني",
    nameLabel: "الاسم",
    prefYearLabel: "السنة الدراسية",
    prefCurrLabel: "المنهج الدراسي",
    btnLogin: "ابدأ التعلم",
    btnGuest: "تابع كضيف",
    welcomeBack: "مرحباً بعودتك،",
    logout: "تسجيل خروج",
    or: "أو",
    
    // Dashboard
    perfTrend: "مؤشر الأداء",
    noQuizData: "لا توجد بيانات اختبارات.",
    quizzesCompleted: "الاختبارات المكتملة",
    avgScore: "متوسط الدرجات",
    recentGen: "سجل دراستك",
    noActivity: "لا يوجد نشاط حديث.",
    noFilterMatch: "لا توجد عناصر تطابق الفلتر.",
    all: "الكل",
    addTag: "إضافة وسم",
    doc: "مستند",
    quizShort: "اختبار",
    chk: "واجب",
    aiProgressReport: "متتبع التقدم الذكي",
    generateAnalysis: "تحليل التقدم",
    refreshAnalysis: "تحديث التحليل",
    clickToAnalyze: "اضغط 'تحليل التقدم' للحصول على تقرير الذكاء الاصطناعي",
    noDataYet: "لا توجد بيانات متاحة بعد",
    overallMastery: "إتقان المستوى الدراسي",
    strengths: "نقاط القوة",
    areasFocus: "نقاط للتحسين",
    recommendedPlan: "الخطة المقترحة",
    analysisGenerated: "تم إنشاء التحليل في",
    generating: "جاري التحليل...",
    
    // Common
    back: "رجوع",
    print: "طباعة",
    exportPdf: "تصدير PDF",
    close: "إغلاق",
    generatedWith: "تم الإنشاء بواسطة Gemini AI",

    // Quiz
    quit: "خروج",
    progress: "التقدم",
    switchToFlash: "التبديل للبطاقات",
    switchToQuiz: "التبديل للاختبار",
    checkAnswer: "تحقق من الإجابة",
    nextQuestion: "السؤال التالي ←",
    seeResults: "عرض النتائج",
    quizComplete: "اكتمل الاختبار!",
    reviewComplete: "اكتملت المراجعة!",
    reviewMistakes: "مراجعة الأخطاء",
    retake: "إعادة الاختبار",
    restartReview: "إعادة المراجعة",
    backDashboard: "عودة للسجل",
    aiCoach: "مدرب الأداء الذكي",
    analyzing: "جاري التحليل...",
    accuracy: "الدقة",
    correct: "صحيح",
    questionsToImprove: "أسئلة للتحسين",
    tryBetter: "حاول الحصول على درجة أفضل",
    tapFlip: "اضغط للقلب",
    answer: "الإجابة",
    previous: "السابق",
    next: "التالي",
    done: "تم",
    exit: "خروج",
    card: "بطاقة"
  }
};